[workspace]
resolver = "2"
members = [
  "crates/kiko-base-commissioning",
  "crates/kiko-expression-core",
  "crates/kiko-eye-protocol",
  "crates/kiko-supervisor-core",
  "crates/kiko-slam",
  "crates/oak-sys",
  "comms/robot-protocol",
  "comms/robot-command-client",
  "comms/robot-server",
  "comms/desktop-client/src-tauri",
  "embedded",
]
default-members = ["crates/kiko-slam"]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace.lints.rust]
unsafe_code = "warn"

[profile.release.package.embedded]
opt-level = "z"
debug = true
