[package]
name = "robot-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.11"
tokio = { version = "1.35", features = ["macros", "rt-multi-thread"] }
prost = "0.12"
chrono = "0.4"

[build-dependencies]
tonic-build = "0.11"
